"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from decouple import config

# Use config() to get the variables from .env
# SECRET_KEY = config("SECRET_KEY")
# Look for the real key in .env first.
# If it's not there (like in GitHub Actions), use the insecure one.
SECRET_KEY = config("SECRET_KEY", default="django-insecure-for-testing-only")

# IMPORTANT: Make sure DEBUG is False in production!
DEBUG = config("DEBUG", default=True, cast=bool)
# DEBUG = config("DEBUG", default=False, cast=bool)

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-zzlk*m@3h*x%1*lspx-edw(agh8jehs8^^^s@x$of!16)(i(dj"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 1. ALLOWED_HOSTS
# In Docker, Nginx and Django talk over a private network.
# We add '*' for development or specific container names for production.
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "web"]

CORS_ALLOWED_ORIGINS = [
    "https://www.my-official-app.com",
    "https://my-app-frontend.vercel.app",
]

"""
# Ensure this is ONLY in your production_settings.py
DEBUG = False
SECURE_SSL_REDIRECT = True  # Redirects http:// to https://
SESSION_COOKIE_SECURE = True  # Browser won't send session cookie over HTTP
CSRF_COOKIE_SECURE = True  # Browser won't send CSRF cookie over HTTP
"""


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",  # 1. Adds the Token table to your DB
    "myApp.apps.MyappConfig",
    "corsheaders",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",  # 2. Look for "Authorization: Token ..."
        "rest_framework.authentication.SessionAuthentication",  # 3. Keep browser login working
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  # No one gets in without a token!
    ],
    # 1. Pagination: Limits results to 10 per page
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,  # Number of posts per page
    # 2. Filtering & Ordering: Enables the engines
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",  # For Filtering
        "rest_framework.filters.OrderingFilter",  # For Ordering
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "5/day",  # Only 5 requests per day for strangers
        "user": "3/minute",  # Only 10 requests per minute for users
    },
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.AcceptHeaderVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1", "v2"],
    # This tells DRF that in your custom media type,
    # the version is identified by the word "version"
    "VERSION_PARAM": "version",
    # This is the "Media Type" part!
    # It tells Django to look for this specific 'base' string.
    "DEFAULT_RENDERER_CLASSES": [
        "myApp.renderers.MyProjectJSONRenderer",  # Add your custom one first!
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    # No VERSION_PARAM needed here for AcceptHeader
    # "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.QueryParameterVersioning",
    # "DEFAULT_VERSION": "v1",
    # "ALLOWED_VERSIONS": ["v1", "v2"],
    # "VERSION_PARAM": "version",  # This is the 'key' in ?version=v1
    # "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    # "DEFAULT_VERSION": "v1",
    # "ALLOWED_VERSIONS": ["v1", "v2"],
    # "VERSION_PARAM": "version",
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),  # Short life for security
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),  # Long life to get new access tokens
    "ROTATE_REFRESH_TOKENS": True,  # Give a new refresh token every time
    "AUTH_HEADER_TYPES": ("Bearer",),  # Use "Bearer <token>" in Postman
}


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Must be at the top!
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # YOUR CUSTOM MIDDLEWARE GOES HERE
    "myApp.middleware.PerformanceTimerMiddleware",
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# settings.py
import sys

# Check if we are running a test
TESTING = "test" in sys.argv

if TESTING:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }
else:
    # Use config() to get the variables from .env
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME", default=str(BASE_DIR / "db.sqlite3")),
            # "NAME": config("DB_NAME"),  # python-decouple syntax
            "USER": config("DB_USER", default=""),
            "PASSWORD": config("DB_PASSWORD", default=""),
            "HOST": config(
                "DB_HOST", default="localhost"
            ),  # You can even set defaults!
            # For Docker we replace host with this line
            # 'HOST': 'db',  # <--- This matches the name in docker-compose.yml
            "PORT": config("DB_PORT", default=""),  # It can automatically convert types
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# settings.py
AUTH_USER_MODEL = "myApp.CustomUser"  # Format: 'app_name.ModelName'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# The ACTUAL folder on your computer where files will be gathered
STATIC_ROOT = BASE_DIR / "staticfiles"

# settings.py
LOGIN_URL = "/admin/login/"


import os

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
