# Generated by Django 6.0.1 on 2026-02-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_body_post_content_post_author_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_email',
            field=models.EmailField(max_length=254),
        ),
    ]
